apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: alb-prod
spec:
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  type: NodePort
  selector:
    app.kubernetes.io/name: nginx